-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 21, 2023 at 01:18 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.0.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `news`
--

-- --------------------------------------------------------

--
-- Table structure for table `comments`
--

CREATE TABLE `comments` (
  `id` int(11) NOT NULL,
  `news_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `comment` varchar(255) NOT NULL,
  `created_at` varchar(255) NOT NULL,
  `updated_at` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `comments`
--

INSERT INTO `comments` (`id`, `news_id`, `name`, `email`, `comment`, `created_at`, `updated_at`) VALUES
(1, 1, 'a', 'admin@gmail.com', 'qqqq', '2022-02-04 18:40:36', '2022-02-04 18:40:36'),
(2, 1, 'a', 'admin@gmail.com', 'waw', '2022-02-04 18:42:28', '2022-02-04 18:42:28'),
(3, 1, 'das', 'dsada', 'das', '2023-04-19 15:07:20', '2023-04-19 15:07:20'),
(4, 25, 'aaa', 'aaa', 'a', '2023-04-20 11:03:30', '2023-04-20 11:03:30'),
(5, 25, 'fsd', 'sdf', 'sdf', '2023-04-20 11:03:40', '2023-04-20 11:03:40'),
(6, 25, 'Full name', 'email@gmail.com', 'commnent', '2023-04-20 11:20:31', '2023-04-20 11:20:31'),
(7, 8, 'test', 'test@gmail.com', 'test component commnet.  sharp rise in bitcoin prices has pushed the cryptocurrency above $30,000 (£24,118) for the first time since 10 June last year, just before the Celsius crypto lending company froze withdra.', '2023-04-20 18:58:21', '2023-04-20 18:58:21'),
(8, 8, 'test', 'test2@sdf.sdf', 'i aurait pu croire que linflation puisse devenir une tendance opportune pour le Bitcoin ? Au cours du de.', '2023-04-20 19:05:13', '2023-04-20 19:05:13'),
(9, 8, 'sdfdsf', 'fsdfds@fgfd.fds', '11Asian shares are slightly lower early on Monday after Switzerland\'s UBS struck a deal to take over peer Credit Suisse. The deal values Credit Suisse at .', '2023-04-20 19:08:08', '2023-04-20 19:08:08'),
(10, 8, 'sdasds', 'adsad@daa.ads', '22 ww vczxv cvxcvz 70 % de hausse : voici le Bitcoin de 2023, outsider et indépendant.', '2023-04-20 19:11:49', '2023-04-20 19:11:49'),
(11, 8, 'sdf', 'fsd@sdf.sdf', 'sdf', '2023-04-20 19:16:47', '2023-04-20 19:16:47');

-- --------------------------------------------------------

--
-- Table structure for table `newsdata`
--

CREATE TABLE `newsdata` (
  `id` int(11) NOT NULL,
  `Source` varchar(255) NOT NULL,
  `Author` varchar(255) NOT NULL,
  `Title` varchar(255) NOT NULL,
  `Description` text NOT NULL,
  `Url` text NOT NULL,
  `urlToImage` text NOT NULL,
  `Published` datetime NOT NULL DEFAULT current_timestamp(),
  `Content` text NOT NULL,
  `Sourceid` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `newsdata`
--

INSERT INTO `newsdata` (`id`, `Source`, `Author`, `Title`, `Description`, `Url`, `urlToImage`, `Published`, `Content`, `Sourceid`) VALUES
(1, 'Gizmodo.com', 'Kyle Barr', 'Here’s How to Find the Original Bitcoin Manifesto in Your Mac', 'An Apple developer left one of the strangest Easter eggs hidden in the macOS, offering a surprising and baffling connection between the Cupertino tech company’s mainline operating system to everybody’s (least) favorite cryptographic digital currency. Read mor…', 'https://gizmodo.com/bitcoin-apple-mac-bitcoin-white-paper-1850307069', 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/176f6f215c9c45306ca8269f8232701e.jpg', '2023-04-06 15:30:00', 'An Apple developer left one of the strangest Easter eggs hidden in the macOS, offering a surprising and baffling connection between the Cupertino tech companys mainline operating system to everybodys… [+3865 chars]', ''),
(2, 'Google News', '', 'Cryptoverse: Bitcoin traders like their options - Reuters', 'Cryptoverse: Bitcoin traders like their options  Reuters', 'https://consent.google.com/ml?continue=https://news.google.com/rss/articles/CBMiXWh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvY3J5cHRvdmVyc2UtYml0Y29pbi10cmFkZXJzLWxpa2UtdGhlaXItb3B0aW9ucy0yMDIzLTA0LTA0L9IBAA?oc%3D5&gl=FR&hl=en-US&cm=2&pc=n&src=1', '', '2023-04-04 05:18:00', 'We use cookies and data to<ul><li>Deliver and maintain Google services</li><li>Track outages and protect against spam, fraud, and abuse</li><li>Measure audience engagement and site statistics to unde… [+1131 chars]', 'google-news'),
(3, 'Google News', '', 'Intel ends its bitcoin mining chip series - Reuters', 'Intel ends its bitcoin mining chip series  Reuters', 'https://consent.google.com/ml?continue=https://news.google.com/rss/articles/CBMiWGh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvaW50ZWwtZW5kcy1pdHMtYml0Y29pbi1taW5pbmctY2hpcC1zZXJpZXMtMjAyMy0wNC0xOC_SAQA?oc%3D5&gl=FR&hl=en-US&cm=2&pc=n&src=1', '', '2023-04-18 18:07:00', 'We use cookies and data to<ul><li>Deliver and maintain Google services</li><li>Track outages and protect against spam, fraud, and abuse</li><li>Measure audience engagement and site statistics to unde… [+1131 chars]', 'google-news'),
(4, 'Business Insider', 'Carla Mozée', 'Michael Saylor\'s MicroStrategy adds to its bitcoin trove, purchasing 1,045 coins for $24 million', 'The business software maker now holds 140,000 bitcoin and the value of that stash was nearly $4 billion with bitcoin trading above $28,000.', 'https://markets.businessinsider.com/news/currencies/bitcoin-microstrategy-cryptocurrency-michael-saylor-coins-buys-holding-value-mstr-2023-4', 'https://i.insider.com/631133643fe7c40019e4f2fd?width=1200&format=jpeg', '2023-04-05 16:47:03', 'Michael Saylor is facing a $100 million lawsuit for tax evasionMarco Bello/Getty Images\r\n<ul>\n<li>MicroStrategy continued to build its bitcoin stash in early April, buying 1,045 coins. </li>\n<li>It b… [+1587 chars]', 'business-insider'),
(5, 'Google News', '', 'Bitcoin near 9-month high as bank turmoil sparks rally - Reuters.com', 'Bitcoin near 9-month high as bank turmoil sparks rally  Reuters.com', 'https://consent.google.com/ml?continue=https://news.google.com/rss/articles/CBMiamh0dHBzOi8vd3d3LnJldXRlcnMuY29tL21hcmtldHMvY3VycmVuY2llcy9iaXRjb2luLW5lYXItOS1tb250aC1oaWdoLWJhbmstdHVybW9pbC1zcGFya3MtcmFsbHktMjAyMy0wMy0yMC_SAQA?oc%3D5&gl=FR&hl=en-US&cm=2&pc=n&src=1', '', '2023-03-20 06:52:00', 'We use cookies and data to<ul><li>Deliver and maintain Google services</li><li>Track outages and protect against spam, fraud, and abuse</li><li>Measure audience engagement and site statistics to unde… [+1131 chars]', 'google-news'),
(6, 'Google News', '', 'Bitcoin pushes past $30000 as investors eye end of rate rises - Reuters', 'Bitcoin pushes past $30000 as investors eye end of rate rises  Reuters', 'https://consent.google.com/ml?continue=https://news.google.com/rss/articles/CBMiZWh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvYml0Y29pbi1wdXNoZXMtcGFzdC0zMDAwMC1pbnZlc3RvcnMtZXllLWVuZC1yYXRlLXJpc2VzLTIwMjMtMDQtMTEv0gEA?oc%3D5%26hl%3Den-CA%26gl%3DCA%26ceid%3DCA:en&gl=FR&hl=en-CA&cm=2&pc=n&src=1', '', '2023-04-11 03:55:00', 'We use cookies and data to<ul><li>Deliver and maintain Google services</li><li>Track outages and protect against spam, fraud, and abuse</li><li>Measure audience engagement and site statistics to unde… [+1131 chars]', 'google-news'),
(7, 'Google News', '', 'Dollar pauses after strong gains on hawkish Fed bets; bitcoin hits ... - Reuters', 'Dollar pauses after strong gains on hawkish Fed bets; bitcoin hits ...  Reuters', 'https://consent.google.com/ml?continue=https://news.google.com/rss/articles/CBMie2h0dHBzOi8vd3d3LnJldXRlcnMuY29tL21hcmtldHMvY3VycmVuY2llcy9kb2xsYXItcGF1c2VzLWFmdGVyLXN0cm9uZy1nYWlucy1oYXdraXNoLWZlZC1iZXRzLWJpdGNvaW4taGl0cy0zMDAwMC0yMDIzLTA0LTExL9IBAA?oc%3D5&gl=FR&hl=en-US&cm=2&pc=n&src=1', '', '2023-04-11 01:47:00', 'We use cookies and data to<ul><li>Deliver and maintain Google services</li><li>Track outages and protect against spam, fraud, and abuse</li><li>Measure audience engagement and site statistics to unde… [+1131 chars]', 'google-news'),
(8, 'The Guardian', 'Alex Hern', 'Bitcoin price rises above $30,000 for first time since June 2022', 'Cyptocurrency’s steady increase in value reignites fears of widespread market manipulationA sharp rise in bitcoin prices has pushed the cryptocurrency above $30,000 (£24,118) for the first time since 10 June last year, just before the Celsius crypto lending c…', 'https://www.theguardian.com/technology/2023/apr/11/bitcoin-price-rises-usd-cyptocurrency-value', 'https://i.guim.co.uk/img/media/557a4b7ba8d4a7ac4ffdc68894f2b3caa276f344/0_235_3551_2132/master/3551.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=56808976844276c471575e281886d474', '2023-04-11 11:15:45', 'A sharp rise in bitcoin prices has pushed the cryptocurrency above $30,000 (£24,118) for the first time since 10 June last year, just before the Celsius crypto lending company froze withdrawals in th… [+6113 chars]', ''),
(9, 'Slashdot.org', 'msmash', 'Intel Discontinues Bitcoin-Mining Blockscale Chips', 'It\'s been just a year since Intel officially announced its Bitcoin-mining Blockscale ASICs, but today the company announced the end of life of its first-gen Blockscale 1000-series chips without announcing any follow-up generations of the chips. From a report:…', 'https://slashdot.org/story/23/04/18/1652237/intel-discontinues-bitcoin-mining-blockscale-chips', 'https://a.fsdn.com/sd/topics/intel_64.png', '2023-04-18 22:00:00', 'We spoke with Intel on the matter, and the company told Tom\'s Hardware that \"as we prioritize our investments in IDM 2.0, we have end-of-lifed the Intel Blockscale 1000 Series ASIC while we continue … [+795 chars]', ''),
(10, 'Business Insider', 'Phil Rosen', 'Apple hiding a bitcoin manifesto in Macs is fueling theories that Steve Jobs was Satoshi Nakamoto, the crypto\'s mysterious inventor', 'The discovery that Apple includes a PDF of Satoshi\'s original bitcoin white paper in every new Mac has sparked fresh conspiracies tied to Jobs.', 'https://markets.businessinsider.com/news/currencies/apple-bitcoin-manifesto-steve-jobs-satoshi-nakamoto-white-paper-cryptocurrency-2023-4', 'https://i.insider.com/6430035a3007470019fe1513?width=1200&format=jpeg', '2023-04-07 13:19:48', 'Steve Jobs.David Paul Morris / Stringer\r\n<ul>\n<li>Technologist Andy Baio wrote this week that he discovered a PDF of the original bitcoin white paper on his Mac.</li>\n<li>The revelation fueled theori… [+3349 chars]', 'business-insider'),
(11, 'Business Insider', 'Huileng Tan', 'Bitcoin\'s nearing a breakout moment — prices topped $30,000 for the first time since June 2022', 'Bitcoin is up about 80% this year so far while Ether is up about 60% in the same period.', 'https://markets.businessinsider.com/news/currencies/bitcoins-breakout-moment-first-time-since-june-2022-2023-4', 'https://i.insider.com/6434df53ca216e001820ff87?width=1200&format=jpeg', '2023-04-11 06:18:31', 'Bitcoin has rallied over $30,000.Anadolu Agency/Getty Images\r\n<ul>\n<li>Bitcoin has rallied above the $30,000 level for the first time since June 2022.</li>\n<li>The gains are driven by expectations th… [+1755 chars]', 'business-insider'),
(12, 'Business Insider', 'prosen@insider.com (Phil Rosen)', 'Bitcoin storms toward its strongest quarter in 2 years with a 72% jump, outperforming the Nasdaq and gold', 'The world\'s largest cryptocurrency is enjoying massive gains even though just a few months ago, some experts warned of a further crash.', 'https://markets.businessinsider.com/news/currencies/bitcoin-price-today-q1-nasdaq-gold-fed-rate-hikes-crypto-2023-3', 'https://i.insider.com/6424307ded593e00183f0aad?width=1200&format=jpeg', '2023-03-29 13:10:39', 'Bitcoin has stormed to a 72% gain over the last three months and is on track for its strongest quarter in two years.\r\nThe token has outperformed both the Nasdaq 100 and gold, which are up 15% and 9%,… [+1167 chars]', 'business-insider'),
(13, 'Business Insider', 'Phil Rosen', 'Who is Satoshi Nakamoto? Crypto fans just celebrated the bitcoin inventor\'s birthday and his legend is as mysterious as ever.', 'Theories swirled this week that Apple visionary Steve Jobs was the legendary Satoshi Nakamoto after the bitcoin white paper was found on macOS.', 'https://markets.businessinsider.com/news/currencies/who-is-satoshi-nakamoto-bitcoin-inventor-crypto-steve-jobs-apple-2023-4', 'https://i.insider.com/643023743007470019fe17e4?width=1200&format=jpeg', '2023-04-07 16:38:23', 'A statue of Satoshi Nakamoto, a presumed pseudonym used by the inventor of Bitcoin, is displayed in Graphisoft Park on September 22, 2021 in Budapest, Hungary.Janos Kummer / Stringer, Getty Images\r\n<… [+4728 chars]', 'business-insider'),
(14, 'Business Insider', 'ztayeb@businessinsider.com (Zahra Tayeb)', 'Jeremy Siegel says bitcoin\'s rush higher will fizzle out once people trust banks again', '', 'https://markets.businessinsider.com/news/currencies/jeremy-siegel-bitcoin-crypto-rally-will-fade-banking-crisis-2023-3', 'https://i.insider.com/52ed527cecad049a6d4ad89c?width=1200&format=jpeg', '2023-03-22 13:38:59', 'Wharton professor Jeremy Siegel has weighed in on bitcoin\'s recent rally, spurred on by the recent banking crisis. \r\n\"My feeling is when people feel they\'re safe in the banks again, bitcoin will go b… [+1226 chars]', 'business-insider'),
(15, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'Bitcoin soars to a 9-month high after Credit Suisse takeover fails to calm banking fears', 'Fundstrat said bitcoin\'s outperformance is a testament to its \"outright resiliency\" when you consider the failures of Signature Bank and Silvergate.', 'https://markets.businessinsider.com/news/currencies/bitcoin-price-9-month-high-credit-suisse-ubs-bank-crisis-2023-3', 'https://i.insider.com/64185980718b5300194b17d2?width=1200&format=jpeg', '2023-03-20 13:46:19', 'Bitcoin surged as much as 4% on Monday amid fears of an ongoing banking crisis that started with the downfall of Silicon Valley Bank earlier this month and has now led to the takeover of Credit Suiss… [+2301 chars]', 'business-insider'),
(16, 'Business Insider', 'Theron Mohamed', 'Warren Buffett just revealed his company plowed $4 billion into stocks last quarter. Here are 8 key takeaways from a new interview.', 'Warren Buffett touted Apple, ripped bitcoin, warned inflation and recession are serious risks, and revealed he\'s been worried about banks for a while.', 'https://markets.businessinsider.com/news/stocks/warren-buffett-stock-portfolio-banks-inflation-recession-apple-paramount-bitcoin-2023-4', 'https://i.insider.com/54031f486bb3f7280dbef4ce?width=1200&format=jpeg', '2023-04-13 17:02:00', 'Warren Buffett.REUTERS/Rick Wilking\r\n<ul>\n<li>Warren Buffett piled about $4 billion into stocks in the first quarter, he revealed this week.</li>\n<li>The investor spoke about banks, bitcoin, Apple, P… [+6202 chars]', 'business-insider'),
(17, 'Business Insider', 'Morgan Chittum', 'The crypto market rally is built on hopes of Fed rate hike slowdown and looming US credit crunch, Galaxy Digital\'s Mike Novogratz says', 'Crypto markets have been mostly trending upward since the start of the year. Bitcoin notched a 10-month high Tuesday, shooting past $30,000.', 'https://markets.businessinsider.com/news/currencies/bitcoin-price-crypto-market-outlook-mike-novogratz-galaxy-digital-fed-2023-4', 'https://i.insider.com/6435a157ca216e001821145a?width=1200&format=jpeg', '2023-04-11 19:20:01', 'Mike Novogratz.Marco Bello / Stringer /Getty Images\r\n\n<ul>\n<li>Bitcoin notched a 10-month high Tuesday amid a broader upswing in crypto markets. </li>\n<li>Galaxy Digital CEO Mike Novogratz said marke… [+2022 chars]', 'business-insider'),
(18, 'Business Insider', 'Theron Mohamed', 'Howard Marks says rock-bottom rates are history, bitcoin has its uses, and AI won\'t replace the best investors. Here are his 8 best quotes from a new interview.', 'Rates won\'t return to zero, the banking fiasco shone a light on bitcoin, and AI wouldn\'t spot Steve Jobs\' or Amazon\'s potential, Howard Marks said.', 'https://markets.businessinsider.com/news/stocks/howard-marks-oaktree-interest-rates-fed-bitcoin-crypto-government-debt-2023-4', 'https://i.insider.com/64395319f62706001942feb0?width=1200&format=jpeg', '2023-04-15 10:46:08', 'Howard Marks.K. Y. Cheng/South China Morning Post/Getty Images\r\n<ul>\n<li>Howard Marks says interest rates won\'t return to zero anytime soon.</li>\n<li>The billionaire investor warns the ballooning US … [+2867 chars]', 'business-insider'),
(19, 'Business Insider', 'Raphael Sanis', 'What is crypto, and is it making a comeback?', 'Cryptocurrencies have been on a wild journey since bitcoin emerged in 2009. The future is still murky, as skeptics say they need to prove their worth.', 'https://www.businessinsider.com/what-is-crypto-and-is-it-making-a-comeback-2023-4', 'https://i.insider.com/643ec50e0a29b400188107b5?width=1200&format=jpeg', '2023-04-18 17:36:11', '<ul>\n<li>Cryptocurrencies had a dreadful year in 2022, with investors losing billions.</li>\n<li>Now, prices of bitcoin and ethereum are recovering.</li>\n<li>But Insider correspondent April Joyner say… [+384 chars]', 'business-insider'),
(20, 'Business Insider', 'prosen@insider.com (Phil Rosen)', 'Michael Saylor\'s MicroStrategy snaps up another 6,455 bitcoin as token rallies, bringing its total holdings to $3.88 billion', 'Saylor\'s software company also paid off the remaining principal on a $205 million loan from failed crypto-friendly bank Silvergate.', 'https://markets.businessinsider.com/news/currencies/microstrategy-bitcoin-crypto-markets-investing-finance-michael-saylor-silvergate-loan-2023-3', 'https://i.insider.com/624c4d26c4cd0500195a1381?width=1200&format=jpeg', '2023-03-27 16:42:50', 'Michael Saylor\'s MicroStrategy bought 6,455 bitcoins over the last five weeks, according to a Friday SEC filing.\r\nThe purchases were made at an average price of about $23,238 per token, and totaled r… [+1307 chars]', 'business-insider'),
(21, 'Business Insider', 'Morgan Chittum', 'Ethereum jumps to its highest price in 8 months ahead of highly anticipated network upgrade', 'Crypto markets have been on a tear despite murky macro conditions from the Fed\'s rate hikes and turmoil in the global banking sector.', 'https://markets.businessinsider.com/news/currencies/ethereum-price-crypto-market-outlook-shanghai-network-upgrade-bitcoin-eth-2023-4', 'https://i.insider.com/642c23e3fcb86b0018030c9f?width=1200&format=jpeg', '2023-04-04 14:33:47', 'Ethereum\'s cryptocurrency ether rose 35% in March, Kraken said.Dado Ruvic/Reuters\r\n<ul>\n<li>Ethereum traded at a 24-hour high of $1,884, price levels not seen since August 2022.</li>\n<li>The Shanghai… [+2274 chars]', 'business-insider'),
(22, 'Business Insider', 'George Glover', 'Crypto stocks rally after bitcoin breaks above $30,000 to hit a 10-month high', 'Shares of crypto-related Coinbase, MicroStrategy, and Marathon Digital look set to build on gains as investors took heart from bitcoin\'s resurgence.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-crypto-bitcoin-30k-coinbase-microstrategy-investing-analysis-2023-4', 'https://i.insider.com/614c4813c2c9630018f5ec68?width=1200&format=jpeg', '2023-04-11 12:15:11', 'Coinbase set to build on gains after bitcoin hit a 10-month high Tuesday.Richard Drew/Associated Press\r\n<ul>\n<li>Crypto-related stocks rose Tuesday after bitcoin broke above $30,000 to hit a 10-month… [+2303 chars]', 'business-insider'),
(23, 'Gizmodo.com', 'Lauren Leffer', '\'The Dumpster Fire Is Out:\' Attorneys for Bankrupt FTX Consider Restarting Exchange', 'While SBF and other former FTX execs face criminal fraud charges, the company\'s attorney says they\'ve recovered $7.3 billion in assets.', 'https://gizmodo.com/ftx-sam-bankman-fried-crypto-sbf-1850331812', 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/110fad4ab8a698a4be70f1d1464dafbe.jpg', '2023-04-13 14:45:00', 'You know that classic zombie movie scene where the everyone thinks the monster is dead, but then suddenly its not?\r\nFTX, the bankrupt crypto exchange that imploded last year, has recouped over $7.3 b… [+2371 chars]', ''),
(24, 'Gizmodo.com', 'Jody Serrano', 'Twitter Partners with eToro to Let Users Buy and Sell Stocks, Crypto', 'Elon Musk’s Twitter, which the billionaire said this week is now being run by his dog, has closed a partnership deal with the online investing platform eToro, proving that the company might not be as radioactive as some people might think. Read more...', 'https://gizmodo.com/twitter-partners-etoro-buy-stocks-crypto-cashtags-1850331598', 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/5b32026cc24af364a349c287a696b5a5.jpg', '2023-04-13 11:50:00', 'Elon Musks Twitter, which the billionaire said this week is now being run by his dog, has closed a partnership deal with the online investing platform eToro, proving that the company might not be as … [+2326 chars]', ''),
(25, 'Slashdot.org', 'msmash', 'Crypto\'s Ethereum Blockchain Completes Its Key Shanghai Software Upgrade', 'The Ethereum blockchain, the most important commercial highway in the digital-asset sector, successfully implemented a widely anticipated software upgrade. From a report: The so-called Shanghai update enables investors to queue up to withdraw Ether coins that…', 'https://tech.slashdot.org/story/23/04/13/0856215/cryptos-ethereum-blockchain-completes-its-key-shanghai-software-upgrade', 'https://a.fsdn.com/sd/topics/software_64.png', '2023-04-13 15:20:00', 'The so-called Shanghai update enables investors to queue up to withdraw Ether coins that they had pledged to help operate the network in return for rewards, a process called staking. Tim Beiko, who h… [+866 chars]', ''),
(26, 'Business Insider', 'htan@insider.com (Huileng Tan)', 'Asian shares open slightly lower, Bitcoin rallies after Switzerland\'s UBS seals deal to acquire Credit Suisse', 'Investors are still looking to the Federal Reserve\'s interest rate decision later this week for further cues.', 'https://markets.businessinsider.com/news/stocks/ubs-acquires-credit-suisse-bank-asian-shares-lower-bitcoin-crisis-2023-3', 'https://i.insider.com/6417b59ffa3bcb001907f1a8?width=1200&format=jpeg', '2023-03-20 02:28:38', 'Asian shares are slightly lower early on Monday after Switzerland\'s UBS struck a deal to take over peer Credit Suisse. The deal values Credit Suisse at around $3.25 billion.\r\nThe development in Europ… [+1614 chars]', 'business-insider'),
(27, 'Xataka.com', 'Enrique Pérez', 'El Bitcoin supera de nuevo los 30.000 dólares: una loca (y frágil) subida en medio de la incertidumbre', 'El Bitcoin ya supera los 30.000 dólares. La criptomoneda más popular está teniendo un inicio de año espectacular, con una subida de más del 82%. En medio de la incertidumbre económica, el Bitcoin está teniendo un resultado más que positivo.\n<!-- BREAK 1 -->\nR…', 'https://www.xataka.com/criptomonedas/bitcoin-supera-30-000-dolares-loca-fragil-subida-medio-incertidumbre-economica', 'https://i.blogs.es/8b7b1e/bitcoin/840_560.jpeg', '2023-04-11 09:30:43', 'El Bitcoin ya supera los 30.000 dólares. La criptomoneda más popular está teniendo un inicio de año espectacular, con una subida de más del 82%. En medio de la incertidumbre económica, el Bitcoin est… [+2321 chars]', ''),
(28, 'Slashdot.org', 'msmash', 'Dogecoin Jumps After Token\'s Symbol Replaces Blue Bird as Twitter Logo', 'Dogecoin (DOGE) rose 12% after the Shiba Inu symbol representing the token replaced the familiar blue bird atop the Twitter homepage. From a report: Elon Musk in the past has suggested the meme coin may offer better payments functionality than bitcoin.\n\n\n\n\n\n\r…', 'https://slashdot.org/story/23/04/03/182219/dogecoin-jumps-after-tokens-symbol-replaces-blue-bird-as-twitter-logo', 'https://a.fsdn.com/sd/topics/twitter_64.png', '2023-04-03 18:02:00', 'The Fine Print: The following comments are owned by whoever posted them. We are not responsible for them in any way.', ''),
(29, 'Hipertextual', 'Gabriel Erard', 'Intel cancela su chip para minar Bitcoin, apenas un año después de anunciarlo', 'La aventura de Intel en el mundo de las criptomonedas ha finalizado de un modo repentino. Tom\'s Hardware reporta que la compañía ha decidido discontinuar Blockscale, su chip dedicado a equipos para minar Bitcoin —conocidos como mineros ASIC—. La noticia sale …', 'http://hipertextual.com/2023/04/intel-cancela-chip-minar-bitcoin', 'https://imgs.hipertextual.com/wp-content/uploads/2023/04/intel-scaled.jpg', '2023-04-18 18:22:13', 'La aventura de Intel en el mundo de las criptomonedas ha finalizado de un modo repentino. Tom\'s Hardware reporta que la compañía ha decidido discontinuar Blockscale, su chip dedicado a equipos para m… [+4462 chars]', ''),
(30, 'Business Insider', 'Morgan Chittum', 'Dogecoin\'s sharp rally fades after brief burst of enthusiasm around Twitter\'s new Shiba Inu logo', 'When Insider reached out for comment on Twitter\'s new Shiba Inu logo, its press email auto-responded with a single poop emoji.', 'https://markets.businessinsider.com/news/currencies/dogecoin-price-elon-musk-twitter-crypto-meme-coin-shiba-inu-2023-4', 'https://i.insider.com/642ec5f5de7d9200193a4314?width=1200&format=jpeg', '2023-04-06 14:36:00', 'Bitcoin and Dogecoin cryptocurrencies.Jakub Porzycki/NurPhoto via Getty Images\r\n<ul>\n<li>Dogecoin has fallen 8% over the past 24 hours following a huge meme-coin rally earlier this week. </li>\n<li>Th… [+1466 chars]', 'business-insider'),
(31, 'MacRumors', 'MacRumors Staff', 'Top Stories: iOS 17 and watchOS 10 Rumors, When to Expect a New iMac, and More', 'WWDC is now just two months away, and we\'re starting to hear a bit more about what we might see with upcoming iOS 17 and watchOS 10 updates that should be unveiled during the keynote.\n\n\n\n\n\nThis week also saw the release of an iOS 16.4.1 bug fix update, anothe…', 'https://www.macrumors.com/2023/04/08/top-stories-ios-17-watchos-10-rumors/', 'https://images.macrumors.com/t/0v6rR6VqVq6JRGH-t2VBONRUGUc=/1600x/article-new/2023/04/top-stories-8apr2023.jpg', '2023-04-08 13:00:00', 'WWDC is now just two months away, and we\'re starting to hear a bit more about what we might see with upcoming iOS 17 and watchOS 10 updates that should be unveiled during the keynote.\r\nThis week also… [+3786 chars]', ''),
(32, 'heise online', 'Andreas Knobloch', 'Zentralafrikanische Republik streicht Bitcoin als gesetzliches Zahlungsmittel', 'Das afrikanische Land war nach El Salvador das zweite, das Bitcoin legalisierte. Nun wird Bitcoin als offizielles Zahlungsmittel wieder abgeschafft.', 'https://www.heise.de/news/Zentralafrikanische-Republik-streicht-Bitcoin-als-gesetzliches-Zahlungsmittel-8515574.html', 'https://heise.cloudimg.io/bound/1200x1200/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/4/1/0/8/5/7/6/shutterstock_1937129161-91f75b37827ffe38.jpg', '2023-04-03 18:55:00', 'Fast ein Jahr, nachdem die Zentralafrikanische Republik, eines der ärmsten Länder Afrikas, die Kryptowährung Bitcoin zum gesetzlichen Zahlungsmittel erklärt hat, beschloss die Nationalversammlung des… [+2751 chars]', ''),
(33, 'Gizmodo.com', 'Kyle Barr', 'Judge Lets AT&T Off the Hook for Crypto Investor SIM Swap Attack', 'One early crypto investor’s hopes to see a major telecom provider pay up for a 2017 crypto heist have been all but dashed. According to unsealed court documents filed last Thursday, the U.S. District Court for the Central District of California shared that AT…', 'https://gizmodo.com/at-t-crypto-hack-sim-card-ellis-pinsky-1850299709', 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/2d2e74d1994ed1e52cb6ff198f3a04a7.jpg', '2023-04-04 20:10:00', 'One early crypto investors hopes to see a major telecom provider pay up for a 2017 crypto heist have been all but dashed. According to unsealed court documents filed last Thursday, the U.S. District … [+3124 chars]', ''),
(34, 'Business Insider', 'Morgan Chittum', 'Mike Novogratz says it\'s crypto\'s moment to shine as markets watch trillions of bad debt spark a global banking fiasco', 'Banks have been sitting on an \"orgy of debt,\" Galaxy CEO Mike Novogratz said, leaving customers exposed to financial losses.', 'https://markets.businessinsider.com/news/currencies/crypto-market-outlook-global-bank-crisis-mike-novogratz-galaxy-digital-2023-3', 'https://i.insider.com/6138995c2534ab0018534131?width=1200&format=jpeg', '2023-03-31 16:00:06', 'Galaxy Digital CEO Mike Novogratz.Lucas Jackson/Reuters\r\n<ul>\n<li>As chaos rips through the banking sector, Mike Novogratz said the case for crypto is more prominent now.</li>\n<li>Banks have been sit… [+2346 chars]', 'business-insider'),
(35, 'Business Insider', 'Morgan Chittum', 'Ethereum drops 7% amid wider crypto sell-off as traders assess rate uncertainty', 'From whales unloading massive positions to broader uncertainty, crypto experts weigh in on what\'s causing the downside pressure.', 'https://markets.businessinsider.com/news/currencies/ethereum-price-crypto-market-crash-bitcoin-doge-solana-inflation-recession-2023-4', 'https://i.insider.com/643fdff83f6f690018de75e5?width=1200&format=jpeg', '2023-04-19 15:13:57', '(Photo illustration by Jonathan Raa/NurPhoto via Getty Images)\r\n<ul>\n<li>Ethereum fell as much as 7% and bitcoin fell 3% in under 30 minutes early Wednesday.</li>\n<li>Altcoins are taking hits too, wi… [+2555 chars]', 'business-insider'),
(36, 'Hackaday', 'Jonathan Bennett', 'This Week in Security: USB Boom! Acropalypse, and a Bitcoin Heist', 'We’ve covered a lot of sketchy USB devices over the years. And surely you know by now, if you find a USB drive, don’t plug it in to your computer. There’s more that could go wrong…', 'https://hackaday.com/2023/03/24/this-week-in-security-usb-boom-acropalypse-and-a-bitcoin-heist/', 'https://hackaday.com/wp-content/uploads/2016/01/darkarts.jpg', '2023-03-24 14:00:23', 'We’ve covered a lot of sketchy USB devices over the years. And surely you know by now, if you find a USB drive, don’t plug it in to your computer. There’s more that could go wrong than just a malicio… [+9006 chars]', ''),
(37, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'US stocks snap 4-day winning streak as job openings fall and JPMorgan boss warns of more bank turmoil', 'There are 1.7 job openings for every unemployed American looking for a job, down from a peak of 2.0 just a few months ago.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-job-opening-fall-suggesting-weaker-economy-2023-4', 'https://i.insider.com/642c767cd335200018dd9e63?width=1200&format=jpeg', '2023-04-04 20:18:13', 'US stocks fell on Tuesday, ending a four-day win streak after new data hints at a slowing economy.\r\nJob openings in the US unexpectedly fell 632,000 to 9.93 million, representing the lowest level sin… [+1020 chars]', 'business-insider'),
(38, 'Mollywhite.net', 'Molly White', 'No, Bitcoin isn’t pumping because it’s a “safe haven” from banks', 'There are more reasonable explanations for the price increase, and more than a few flaws with the \"safe haven\" narrative.', 'https://newsletter.mollywhite.net/p/no-bitcoin-isnt-pumping-because-its', 'https://substackcdn.com/image/fetch/w_1200,h_600,c_limit,f_jpg,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F37c2d065-d293-4189-8162-d35974c4f4de_1218x745.png', '2023-03-22 02:00:17', 'As Silvergate Bank, Silicon Valley Bank, and Signature Bank all collapsed in short succession, the price of Bitcoin surged.\r\nAs one group of insufferable multimillionaires was coming down from the pa… [+12038 chars]', ''),
(39, 'AppleInsider', 'news@appleinsider.com (Andrew Orr)', 'Man who claims to be Bitcoin creator eyes lawsuit against Apple', 'The Bitcoin whitepaper was recently discovered to be embedded in several versions of macOS, and now a person who claims to be the creator of Bitcoin is accusing Apple of copyright violation.Latest Bitcoin controversyJust two days ago, on April 5, a Mac user d…', 'https://appleinsider.com/articles/23/04/07/man-who-claims-to-be-bitcoin-creator-eyes-lawsuit-against-apple', 'https://photos5.appleinsider.com/gallery/53864-108358-bitcoin-xl.jpg', '2023-04-07 15:49:24', 'Latest Bitcoin controversy\r\nAppleInsider may earn an affiliate commission on purchases made through links on our site.\r\nThe Bitcoin whitepaper was recently discovered to be embedded in several versio… [+1751 chars]', ''),
(40, 'heise online', 'Mark Mantel', 'Blockscale: Intel gibt seine Bitcoin-Miner auf', 'Weitere Konsolidierung bei Intel: Die Firma stellt die Entwicklung von ASICs fürs Krypto-Mining ein, schließt eine Wiederkehr aber nicht aus.', 'https://www.heise.de/news/Blockscale-Intel-gibt-seine-Bitcoin-Miner-auf-8971444.html', 'https://heise.cloudimg.io/bound/1200x1200/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/4/1/4/5/4/7/2/Intel_Bitcoin-4cda2db81899e691.jpg', '2023-04-19 08:04:00', 'Intel hat den Produktionsstopp seiner anwendungsspezifischen Schaltungen (ASICs) fürs Mining der Kryptowährung Bitcoin bekannt gegeben. Unternehmenskunden können Modelle aus der aktuellen Blockscale-… [+2376 chars]', ''),
(41, 'Business Insider', 'Theron Mohamed', 'Warren Buffett predicts more bank failures, dismisses bitcoin buyers as gamblers, and warns inflation and recession are serious threats in a new interview. Here are the 14 best quotes.', 'Warren Buffett touted the immense value of Apple\'s products, joked his planned successor does all the work, and asked if ChatGPT is good for society.', 'https://markets.businessinsider.com/news/stocks/warren-buffett-banking-crisis-bitcoin-inflation-recession-apple-chatgpt-abel-2023-4', 'https://i.insider.com/61695bfc38c1960018300702?width=1200&format=jpeg', '2023-04-13 10:51:57', 'Warren Buffett.Alex Wong / Getty Images\r\n<ul>\n<li>Warren Buffett predicted more banks will fail and compared bitcoin fans to gamblers.</li>\n<li>He warned inflation and recession are major risks, prai… [+4316 chars]', 'business-insider'),
(42, 'Business Insider', 'jsor@insider.com (Jennifer Sor)', 'US stocks climb as banking fears ease and investors focus on key Fed meeting', 'Regional bank stocks continued to recover after Treasury Secretary Janet Yellen said the government could protect customer deposits at smaller banks.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-dow-sp500-fed-banking-fears-ease-2023-3', 'https://i.insider.com/5f3533deb4bb1c001df52fe2?width=1200&format=jpeg', '2023-03-21 13:44:06', 'US stocks rose on Tuesday as banking fears eased and investors turned their attention to the Federal Open Markets Committee meeting. \r\nTreasury Secretary Janet Yellen said the government is ready to … [+1048 chars]', 'business-insider'),
(43, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'US stocks end higher in volatile session as traders assess rate outlook and bank concerns', 'Volatile trading on Thursday saw the S&P 500 erase a gain of nearly 2% as investors geared up for more comments from Treasury Secretary Janet Yellen.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-traders-assess-bank-concerns-interest-rates-2023-3', 'https://i.insider.com/640a33ef08f27b0018488f24?width=1200&format=jpeg', '2023-03-23 20:04:27', 'US stocks suffered severe whiplash on Thursday as investors continued to digest the Federal Reserve\'s latest interest rate hike and fresh concerns of a US banking crisis.\r\nThe Fed hiked interest rate… [+1242 chars]', 'business-insider'),
(44, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'US stocks climb as investors shake off bank concerns ahead of new economic data', 'Jobless claims on Thursday will give investors a sense of how strong the job market is, while PCE data on Friday will show what inflation is doing.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-investors-shake-off-bank-contagion-fears-2023-3', 'https://i.insider.com/5f3ac652ea6ce0002839ac80?width=1200&format=jpeg', '2023-03-29 20:08:54', 'US stocks surged on Wednesday as investors got more comfortable with the idea that the US banking system is not on the brink of a crisis following the collapse of Silicon Valley Bank.\r\nTechnology sto… [+1202 chars]', 'business-insider'),
(45, 'Business Insider', 'mchittum@insider.com (Morgan Chittum)', 'US stocks rise as traders assess jobs data and bet bank crisis has faded', 'Applications for US unemployment benefits ticked higher last week, but have stayed low in a still-tight labor market.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-inflation-fed-interest-rates-bonds-jobs-report-2023-3', 'https://i.insider.com/642584b9b643e80019df7933?width=1200&format=jpeg', '2023-03-30 13:39:28', 'US stocks climbed on Thursday as traders mulled fresh jobs data and continued to move past concerns around the state of the banking sector following this month\'s string of bank failures. \r\nApplicatio… [+1037 chars]', 'business-insider'),
(46, 'Business Insider', 'jsor@insider.com (Jennifer Sor)', 'US stocks jump as investors prepare for interest rate decision from the Fed', 'The Fed is expected to address the banking turmoil and inflation when delivering its interest rate decision on Wednesday.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-dow-sp500-fed-meeting-rates-banks-2023-03', 'https://i.insider.com/640f6c76f724e7001800caf6?width=1200&format=jpeg', '2023-03-21 20:05:53', 'US stocks rose on Tuesday as investors prepared for the Fed\'s next interest rate decision while the bank sector rallied on prospects for more deposit insurance.\r\nCentral bankers began their two-day F… [+982 chars]', 'business-insider'),
(47, 'Business Insider', 'Phil Rosen', 'How Warren Buffett\'s Berkshire Hathaway can navigate the looming economic turmoil', 'Top Buffett historians and financial pros shared how the conglomerate can withstand a looming recession and scoop up bargains along the way.', 'https://www.businessinsider.com/how-warren-buffetts-berkshire-hathaway-can-navigate-economic-turmoil-2023-4', 'https://i.insider.com/642ed65d2a659a0019a6a8f0?width=1200&format=jpeg', '2023-04-07 10:12:12', 'Markets are closed today but the Opening Bell newsletter rings nonetheless. Phil Rosen here — good to see you. The main thing to watch today is the March jobs report, which is due at 8:30 a.m. ET. Wh… [+3157 chars]', 'business-insider'),
(48, 'Gigazine.net', '@GIGAZINE', 'Mojave以降のmacOSに「ビットコインの論文」が隠されていることが判明、保存場所はココ', 'ビットコインが「サトシ・ナカモト」と名乗る匿名の研究者によって開発されたことは広く知られています。新たに、2018年にリリースされた「macOS Mojave」以降のmacOSに「サトシ・ナカモトが記したビットコインの論文」が初期状態で保存されていることが明らかになりました。続きを読む...', 'https://gigazine.net/news/20230406-macos-bitcoin-whitepaper/', 'https://i.gzn.jp/img/2023/04/06/macos-bitcoin-whitepaper/00.png', '2023-04-06 11:00:00', '2018macOS MojavemacOS\r\nThe Bitcoin Whitepaper Is Hidden in Every Modern Copy of macOS - Waxy.orghttps://waxy.org/2023/04/the-bitcoin-whitepaper-is-hidden-in-every-modern-copy-of-macos/\r\nFinderMacinto… [+382 chars]', ''),
(49, 'Rongarret.info', 'Ron', 'A systematic critique of Bitcoin\'s value proposition', '1. Introduction This essay was originally entitled \"Bitcoin\'s design contains the seeds of its own destruction\".  The thesis was going to be...', 'http://blog.rongarret.info/2023/04/a-systematic-critique-of-bitcoins-value.html', '', '2023-04-12 18:02:02', '1. Introduction\r\nThis essay was originally entitled \"Bitcoin\'s design contains the seeds of its own destruction\".  The thesis was going to be that Bitcoin\'s security depends entirely on consuming vas… [+30728 chars]', ''),
(50, 'MakeUseOf', 'Elvis Gwaro', 'What Is the Bitcoin Liquid Sidechain and How Does It Work?', 'Bitcoin isn\'t fast enough, but the Bitcoin Liquid sidechain could be the resolution.', 'https://www.makeuseof.com/what-is-bitcoin-liquid-sidechain/', 'https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/03/person-wearing-glasses-with-bitcoin-lenses-feature.jpg', '2023-03-27 13:45:16', 'One of the biggest issues facing Bitcoin is scalability and speed. Bitcoin\'s underlying technology isn\'t particularly fast and cannot process many transactions simultaneously. That\'s a problem for th… [+8512 chars]', ''),
(51, 'Xataka.com', 'Enrique Pérez', 'Ethereum está recortando distancia al Bitcoin con una fórmula ganadora: ser más descentralizado que nunca', 'El \'cripto invierno\' ha quedado atrás. Si el Bitcoin lleva un 2023 muy bueno, la segunda criptomoneda más importante está teniendo un camino similar. Ethereum se encuentra en un momento crítico, pues estos días se ha completado Shapella, su actualización más …', 'https://www.xataka.com/criptomonedas/ethereum-esta-recortando-distancia-al-bitcoin-formula-ganadora-ser-descentralizado-que-nunca', 'https://i.blogs.es/b9c1dd/ethereum/840_560.jpeg', '2023-04-17 10:00:44', 'El \'cripto invierno\' ha quedado atrás. Si el Bitcoin lleva un 2023 muy bueno, la segunda criptomoneda más importante está teniendo un camino similar. Ethereum se encuentra en un momento crítico, pues… [+3126 chars]', ''),
(52, 'Business Insider', 'mchittum@insider.com (Morgan Chittum)', 'US stocks close higher as markets assess fresh bank woes and recession fears', 'Key government bond yields tumbled to six-month lows as traders wager the Fed is nearing the end of its tightening cycle.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-wall-street-bonds-bank-crisis-equities-2023-3', 'https://i.insider.com/640f546aa3b2a10018b2b2f1?width=1200&format=jpeg', '2023-03-24 20:18:02', 'US stocks ended higher on Friday as investors rallied to end the day in the green, throwing off new banking fears out of Europe.\r\nAll three major indexes ended the day higher, capping off another tum… [+1407 chars]', 'business-insider'),
(53, 'Business Insider', 'mchittum@insider.com (Morgan Chittum)', 'XRP surges 10% on speculation the CFTC\'s Binance suit could impact the token developer\'s monumental SEC case', 'A win against the agency would be a big victory for Ripple, and would also offer some further clarity on future regulatory treatment for many tokens.', 'https://markets.businessinsider.com/news/currencies/xrp-price-crypto-ripple-sec-case-binance-lawsuit-cftc-news-2023-3', 'https://i.insider.com/60265f2e2edd0f001a8d5727?width=1200&format=jpeg', '2023-03-29 15:35:04', 'XRP, the cryptocurrency issued by Ripple, is surging on rumors surrounding outcome of its long-running legal fight with the Securities and Exchange Commission. \r\nThe crypto is up 10% in the past 24 h… [+1581 chars]', 'business-insider'),
(54, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'Tech rally leads US stocks higher as investors refocus on rates after bank fears recede', 'The market is expecting at least two interest rate cuts from the Federal Reserve by the end of this year following the banking crisis.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-tech-stocks-lead-interest-rates-outlook-2023-3', 'https://i.insider.com/5fecc995a644880018193e20?width=1200&format=jpeg', '2023-03-29 13:39:53', 'US stocks surged on Wednesday, led by technology shares, as investors refocus away from the US banking crisis and towards the direction of interest rates through the rest of the year.\r\nFollowing the … [+1357 chars]', 'business-insider'),
(55, 'Business Insider', 'mchittum@insider.com (Morgan Chittum)', 'Cathie Wood\'s Ark Invest dumps $13.5 million of Coinbase stock as crypto exchange notches 7-month highs', 'The famed money manager now holds a 7% stake in Coinbase worth $837 million, after shares jumped 30% in the last week.', 'https://markets.businessinsider.com/news/stocks/stock-market-picks-cathie-woods-ark-invest-coinbase-crypto-exchange-2023-3', 'https://i.insider.com/633c32e96427060019ef2f65?width=1200&format=jpeg', '2023-03-22 14:03:06', 'Cathie Wood\'s Ark Invest sold $13.5 million worth of Coinbase stock, dumping 160,887 shares from the firm\'s Ark Fintech Innovation exchange-traded fund Tuesday.\r\nThe famed money manager now holds $83… [+1428 chars]', 'business-insider'),
(56, 'Business Insider', 'mchittum@insider.com (Morgan Chittum)', 'US stocks trade mixed as investors assess banking turmoil after UBS takeover of Credit Suisse', 'Regional bank shares remained under pressure as investors eye further contagion risk. First Republic stock fell after its credit rating was slashed again.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-banking-crisis-ubs-credit-suisse-2023-3', 'https://i.insider.com/64185991718b5300194b17da?width=1200&format=jpeg', '2023-03-20 13:48:31', 'US stocks were mostly higher on Monday following a takeover deal of Credit Suisse by UBS over the weekend in an effort to calm concerns of a global banking crisis. \r\nOn Sunday, UBS bought its smaller… [+1597 chars]', 'business-insider'),
(57, 'Business Insider', 'ztayeb@businessinsider.com (Zahra Tayeb)', 'The banking turmoil is a win for stocks as the Fed is opening the cash spigot, a top fund manager says', 'Chaos in the US banking system is actually a good thing for stocks because investors are pricing in Fed cash injections into the economy, Unlimited Funds\' Bob Elliott said.', 'https://markets.businessinsider.com/news/stocks/us-stock-market-outlook-banking-turmoil-fed-liquidity-injection-2023-3', 'https://i.insider.com/635b0b3c6c9ef4001812f889?width=1200&format=jpeg', '2023-03-27 15:33:05', 'The US banking turmoil is a win for stocks because it has prompted the Federal Reserve to pump more cash into the financial system, according to a top fund manager. \r\nIn a CNBC interview on Friday, B… [+1419 chars]', 'business-insider'),
(58, 'heise online', 'Adam Popescu', 'Nationalpark in Afrika: Bitcoin-Mining soll Gorillas schützen', 'Um seine Wälder und die berühmte Tierwelt zu schützen, hat der Nationalpark Virunga im Kongo eine Bitcoin-Mining-Farm eröffnet. Das Projekt ist umstritten.', 'https://www.heise.de/hintergrund/Nationalpark-in-Afrika-Bitcoin-Mine-soll-Gorillas-schuetzen-8003460.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag', 'https://heise.cloudimg.io/bound/1200x1200/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/4/0/6/9/6/1/4/aufmacher_bitcoin_mine-a7b6b60994ee0adb.jpg', '2023-03-27 05:00:00', 'Inhaltsverzeichnis\r\nDie weltweit erste Mining-Farm zum Schürfen der Kryptowährung Bitcoin, die von einem Nationalpark betrieben wird, steht in Luviro, einem Weiler außerhalb des Virunga-Parks. Die nö… [+4211 chars]', ''),
(59, 'heise online', 'Adam Popescu', 'Krypto-Geld für Artenschutz? Ein Nationalpark geht diesen Weg mit Bitcoin-Mining', 'Um seine Wälder und die berühmte Tierwelt zu schützen, hat der Nationalpark Virunga im Kongo eine Bitcoin-Mining-Farm eröffnet. Das Projekt ist umstritten.', 'https://www.heise.de/hintergrund/Krypto-Geld-fuer-Artenschutz-Ein-Nationalpark-geht-diesen-Weg-mit-Bitcoin-Mining-8003460.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag', 'https://heise.cloudimg.io/bound/1200x1200/q85.png-lossy-85.webp-lossy-85.foil1/_www-heise-de_/imgs/18/4/0/6/9/6/1/4/aufmacher_bitcoin_mine-a7b6b60994ee0adb.jpg', '2023-03-27 05:00:00', 'Inhaltsverzeichnis\r\nDie weltweit erste Mining-Farm zum Schürfen der Kryptowährung Bitcoin, die von einem Nationalpark betrieben wird, steht in Luviro, einem Weiler außerhalb des Virunga-Parks. Die nö… [+4213 chars]', ''),
(60, 'MarketWatch', 'Frances Yue', 'Crypto: Bitcoin falls after Fed chair Powell said interest rate cuts in 2023 are not likely', 'Bitcoin fell Wednesday as the Fed raised its key interest rate by a quarter of a percentage point, as widely expected, while the Fed chairman Jerome Powell said it’s “the most likely case” that the central bank would refrain from cutting its key interest rate…', 'https://www.marketwatch.com/story/bitcoin-falls-after-fed-chair-powell-said-interest-rate-cuts-in-2023-are-not-likely-b6001999', 'https://images.mktw.net/im-701580/social', '2023-03-22 18:50:00', 'Bitcoin fell Wednesday after the Federal Reserve raised its key interest rate by a quarter of a percentage point, as widely expected, while the Fed chairman Jerome Powell said its the most likely cas… [+1339 chars]', ''),
(61, '9to5Mac', 'Filipe Espósito', 'Here’s why macOS has the Bitcoin whitepaper hidden in its files', 'It’s not unusual to have a few easter eggs hidden in operating systems, and it’s no different with Apple’s. However, some users recently discovered something intriguing. Every copy of macOS has the original Bitcoin whitepaper hidden in its internal files. Whi…', 'https://9to5mac.com/2023/04/06/macos-bitcoin-whitepaper-hidden/', 'https://i0.wp.com/9to5mac.com/wp-content/uploads/sites/6/2023/04/macOS-Bitcoin-whitepaper.jpg?resize=1200%2C628&quality=82&strip=all&ssl=1', '2023-04-06 22:40:52', 'It’s not unusual to have a few easter eggs hidden in operating systems, and it’s no different with Apple’s. However, some users recently discovered something intriguing. Every copy of macOS has the o… [+3439 chars]', ''),
(62, 'Block.xyz', '', 'Block\'s Response to Inaccurate Short Seller Report', 'We intend to work with the SEC and explore legal action against Hindenburg Research for the factually inaccurate and misleading report they shared about our Cash App business today. Hindenburg is known for these types of attacks, which are designed solely to …', 'https://investors.block.xyz/news/news-details/2023/Blocks-Response-to-Inaccurate-Short-Seller-Report/default.aspx', '', '2023-03-23 17:34:45', 'DISTRIBUTED-WORK-MODEL/SAN FRANCISCO--(BUSINESS WIRE)-- \r\nWe intend to work with the SEC and explore legal action against Hindenburg Research for the factually inaccurate and misleading report they s… [+1284 chars]', ''),
(63, 'Substack.com', 'Noah Smith', 'In which Balaji gives away at least a million dollars', 'Also, the dollar is not going to collapse.', 'https://noahpinion.substack.com/p/in-which-balaji-gives-away-at-least', 'https://substackcdn.com/image/fetch/w_1200,h_600,c_limit,f_jpg,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F6c1453d0-cafc-44a4-aaec-b13f36c2431f_1200x720.jpeg', '2023-03-20 16:49:00', 'Having known Balaji Srinivasan for more than half of my life, I can attest that he is a man of deeply held beliefs who is bold in his business dealings. Thus, if anyone I know was going to bet some p… [+2326 chars]', ''),
(64, 'AppleInsider', 'news@appleinsider.com (Wesley Hilliard)', 'Bitcoin whitepaper found hidden in macOS with unknown \'Virtual Scanner II\' app', 'Satoshi Nakamoto\'s Bitcoin whitepaper can be found in any Mac running macOS Catalina or newer, but no one knows why.The Bitcoin whitepaper his hidden within macOSThere are a lot of hidden files on macOS that won\'t appear unless the user is performing a specif…', 'https://appleinsider.com/articles/23/04/05/bitcoin-whitepaper-found-hidden-in-macos-with-unknown-virtual-scanner-ii-app', 'https://photos5.appleinsider.com/gallery/53841-108287-bitcoin-xl.jpg', '2023-04-05 23:03:29', 'The Bitcoin whitepaper his hidden within macOS\r\nAppleInsider may earn an affiliate commission on purchases made through links on our site.\r\nSatoshi Nakamoto\'s Bitcoin whitepaper can be found in any M… [+1839 chars]', ''),
(65, 'Journal du geek', 'Tristan', 'Le “livre blanc” du Bitcoin était caché dans macOS depuis 5 ans', 'Le Bitcoin est aujourd\'hui la devise numérique al plus populaire au monde, son \"livre blanc\" écrit en 2008 en explique les grands principes. \nLe “livre blanc” du Bitcoin était caché dans macOS depuis 5 ans', 'https://www.journaldugeek.com/2023/04/07/le-livre-blanc-du-bitcoin-etait-cache-dans-macos-depuis-5-ans/', 'https://www.journaldugeek.com/content/uploads/2022/02/comment-vendre-bitcoin.jpg', '2023-04-07 14:30:43', 'Le Bitcoin est aujourd\'hui la devise numérique al plus populaire au monde, son \"livre blanc\" écrit en 2008 en explique les grands principes.Andy Baio est un développeur assez connu aux États-Unis. Il… [+2787 chars]', '');
INSERT INTO `newsdata` (`id`, `Source`, `Author`, `Title`, `Description`, `Url`, `urlToImage`, `Published`, `Content`, `Sourceid`) VALUES
(66, 'The Guardian', 'Emma Beddington', 'What has my terrifying fridge taught me? I am too relaxed about best before dates | Emma Beddington', 'In our culinary catacomb, the unwary visitor is greeted by explosive kimchi, mould-capped pesto, tahini like concrete and a vat of vintage vinegars“Does everyone,” the film critic Anne Billson asked on Twitter, “have an evil jar in their fridge?” To which sur…', 'https://www.theguardian.com/commentisfree/2023/apr/10/fridge-best-before-dates-kimchi-pesto-tahini', 'https://i.guim.co.uk/img/media/8f8782be0f0cbac07bc6c32226bfce0513636609/82_100_4876_2926/master/4876.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctb3BpbmlvbnMucG5n&enable=upscale&s=40f55513312944f31c9f084f4684a397', '2023-04-10 06:00:12', 'Does everyone, the film critic Anne Billson asked on Twitter, have an evil jar in their fridge? To which surely the correct answer is: Only one? Lightweight. We have a whole fridge shelf dedicated to… [+2000 chars]', ''),
(67, 'Golem.de', 'Daniel Ziegener', 'SVB und Credit Suisse: Bitcoin profitiert weiter von der Bankenkrise', 'Nachdem Kryptowährungen selbst ein krisenreiches Jahr hinter sich haben, kehren die Anleger nun anscheinend zu Bitcoin und Ethereum zurück. (Bitcoin, Silicon Valley)', 'https://www.golem.de/sonstiges/zustimmung/auswahl.html?from=https%3A%2F%2Fwww.golem.de%2Fnews%2Fsvb-und-credit-suisse-bitcoin-profitiert-weiter-von-der-bankenkrise-2303-172769.html&referer=https%3A%2F%2Ft.co%2F555c393a85', '', '2023-03-20 13:37:02', 'Besuchen Sie Golem.de wie gewohnt mit Werbung und Tracking,\r\n indem Sie der Nutzung aller Cookies zustimmen.\r\n Details zum Tracking finden Sie im Privacy Center.\r\nSkript wurde nicht geladen. Informat… [+607 chars]', ''),
(68, 'Golem.de', 'Daniel Ziegener', 'Kryptoleitwährung im Aufwind: Bitcoin erstmals seit Monaten wieder über 30.000 US-Dollar', 'Im Juni 2022 durchbrach die größte Kryptowährung den Wert von oben. Neun Monate später hat sich der Bitcoin-Kurs wieder erholt. (Bitcoin, Silicon Valley)', 'https://www.golem.de/sonstiges/zustimmung/auswahl.html?from=https%3A%2F%2Fwww.golem.de%2Fnews%2Fkryptoleitwaehrung-im-aufwind-bitcoin-erstmals-seit-monaten-wieder-ueber-30-000-us-dollar-2304-173342.html&referer=https%3A%2F%2Ft.co%2Fbf065d3080', '', '2023-04-11 13:46:01', 'Besuchen Sie Golem.de wie gewohnt mit Werbung und Tracking,\r\n indem Sie der Nutzung aller Cookies zustimmen.\r\n Details zum Tracking finden Sie im Privacy Center.\r\nSkript wurde nicht geladen. Informat… [+607 chars]', ''),
(69, 'Business Insider', 'gglover@insider.com (George Glover)', 'Top economist David Rosenberg said the Fed should put bigger rate hikes back on the table after bouts of \'speculative lunacy\'', '\"I am starting to wonder if 50 basis points shouldn\'t be back on the table,\" Rosenberg said, referring to the Fed\'s upcoming interest-rate decision.', 'https://markets.businessinsider.com/news/stocks/david-rosenberg-top-economist-stock-market-news-fed-interest-rates-2023-3', 'https://i.insider.com/641acdc4956507001988eb68?width=1200&format=jpeg', '2023-03-22 11:54:12', 'The Federal Reserve should consider bringing in a bigger-than-expected rate hike Wednesday to crush a recent bout of speculation in markets, according to top economist David Rosenberg.\r\n\"After this r… [+1834 chars]', 'business-insider'),
(70, 'Golem.de', 'Moritz Tremmel', 'Sprengsatz bei DM: Bitcoin-Erpresser vor Gericht', 'Mit einem detonierten Sprengsatz hat ein 53-Jähriger die Drogeriekette DM um mehrere Hunderttausend Euro in Bitcoin erpresst. Nun hat er gestanden. (Bitcoin, Security)', 'https://www.golem.de/sonstiges/zustimmung/auswahl.html?from=https%3A%2F%2Fwww.golem.de%2Fnews%2Fdm-bitcoin-erpresser-vor-gericht-2303-172916.html&referer=https%3A%2F%2Ft.co%2F561c6eebc1', '', '2023-03-24 11:26:02', 'Besuchen Sie Golem.de wie gewohnt mit Werbung und Tracking,\r\n indem Sie der Nutzung aller Cookies zustimmen.\r\n Details zum Tracking finden Sie im Privacy Center.\r\nSkript wurde nicht geladen. Informat… [+607 chars]', ''),
(71, 'VentureBeat', 'Adrian Krion, Spielworks', 'From battlefield to homefront: AR is bigger than the metaverse', 'Military uses of AR and VR can trickle down to the gaming and consumer worlds, much as the government-created internet did.', 'https://venturebeat.com/virtual/from-battlefield-to-homefront-ar-bigger-than-metaverse/', 'https://venturebeat.com/wp-content/uploads/2022/03/GettyImages-1187160851.jpg?w=1200&strip=all', '2023-04-17 20:07:00', 'Join top executives in San Francisco on July 11-12, to hear how leaders are integrating and optimizing AI investments for success. Learn More\r\nThroughout modern history, the military has supplemented… [+1583 chars]', ''),
(72, 'Business Insider', 'Hallam Bullock', 'After gaining control of our reporter\'s phone, a hacker ripped her off for $10,000. She set out to find them.', 'In today\'s edition of 10 Things in Tech: TikTok has changed the dance industry, Musk\'s $1 million bounty, and your Mac may contain a hidden manifesto.', 'https://www.businessinsider.com/hacker-hunting-elon-musk-apple-bitcoin-bob-lee-lex-fridman-2023-4', 'https://i.insider.com/642eea6fde7d9200193a4bc7?width=1200&format=jpeg', '2023-04-08 11:30:13', 'Do you eat meat, reader? If so, what is your meatball of choice — beef, chicken… mammoth? Yes, you read that right. Newsletter editor Hallam Bullock here, coming to you from London.An Australian star… [+4054 chars]', 'business-insider'),
(73, 'Business Insider', 'Morgan Chittum', 'US stocks end mixed as soft jobs data revives fears of a looming recession', 'UBS Global Wealth Management\'s CIO said recession risks have increased. Meanwhile, the Nasdaq shed over 1%, while gold traded near all-time highs.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-inflation-recession-nasdaq-jobs-data-bonds-dow-2023-4', 'https://i.insider.com/642dcd432a659a0019a6910d?width=1200&format=jpeg', '2023-04-05 20:13:52', 'Photo by TIMOTHY A. CLARY/AFP via Getty Images)\r\n<ul>\n<li>US stocks were mixed on Wednesday as traders digested weak jobs data. </li>\n<li>The Nasdaq Composite fell 1% as traders retreated on recessio… [+2401 chars]', 'business-insider'),
(74, 'Business Insider', 'Morgan Chittum', 'Billionaire crypto bull Mike Novogratz says the US is headed for a credit crisis and a dramatic economic slowdown that will make bitcoin\'s investment case stronger', '\"The government has kind of gone full jihad against crypto,\" Galaxy Digital CEO Mike Novogratz said.', 'https://markets.businessinsider.com/news/currencies/credit-crisis-recession-crypto-market-outlook-mike-novogratz-galaxy-digital-2023-4', 'https://i.insider.com/643816995f081b0019c0fe28?width=1200&format=jpeg', '2023-04-13 15:46:22', 'Mike Novogratz.Marco Bello / Stringer /Getty Images\r\n<ul>\n<li>Galaxy Digital CEO Mike Novogratz said the US is heading towards a credit crisis and a dramatic economic downturn.</li>\n<li>The crypto bu… [+1895 chars]', 'business-insider'),
(75, 'Business Insider', 'George Glover', 'FTX could relaunch - and one of its former VC backers may lead a $250 million funding round to revive the failed exchange, report says', 'FTX executives are still in the early stages of deciding whether reviving the failed crypto exchange would be worthwhile.', 'https://markets.businessinsider.com/news/currencies/ftx-relaunch-tribe-capital-vc-crypto-crash-sam-bankman-fried-2023-4', 'https://i.insider.com/643f9f5d632fda00180393e8?width=1200&format=jpeg', '2023-04-19 09:11:10', 'The logo of FTX at the entrance of the FTX Arena in Miami, Florida.Marco Bello/Reuters\r\n<ul>\n<li>Tribe Capital may lead a $250 million funding round to reboot FTX, according to Bloomberg.</li>\n<li>Tr… [+2315 chars]', 'business-insider'),
(76, 'Business Insider', 'Carla Mozée', 'US stocks fall as investors assess latest earnings and climbing bond yields', 'The S&P 500 was on course to fall for the first time after two straight days of gains. Morgan Stanley and Netflix shares were on the move.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-dow-nasdaq-earnings-bond-yields-banks-netflix-2023-4', 'https://i.insider.com/62bad7662224c3001813f01e?width=1200&format=jpeg', '2023-04-19 13:44:18', 'Traders on the floor of the New York Stock Exchange.Spencer Platt/Getty Images\r\n<ul>\n<li>US stocks fell Wednesday, feeling the pinch from rising bond yields and as investors mulled earnings. </li>\n<l… [+2148 chars]', 'business-insider'),
(77, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'An end to Fed rate hikes is just one reason why technology stocks are holding up amid the broader market chaos', 'The market now expects the Fed to cut interest rates by at least 100 basis points between now and the end of the year, according to the FedWatch Tool.', 'https://markets.businessinsider.com/news/stocks/stock-market-analysis-end-fed-rate-hikes-technology-resilience-inflation-2023-3', 'https://i.insider.com/5fac4c2a7f8f4200182a65c2?width=1200&format=jpeg', '2023-03-24 14:19:50', 'Despite a banking crisis that led to the biggest bank failure since 2008, technology stocks are doing just fine.\r\nSince Silicon Valley Bank was taken over by the FDIC on March 10, the technology sect… [+2158 chars]', 'business-insider'),
(78, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'Nvidia says crypto \'doesn\'t bring anything useful for society\' as it turns its focus to artificial intelligence', '\"They bought a lot of stuff, and then eventually it collapsed, because it doesn\'t bring anything useful for society,\" Nvidia\'s CTO said.', 'https://markets.businessinsider.com/news/stocks/nvidia-crypto-doesnt-bring-anything-useful-for-society-ai-focus-2023-3', 'https://i.insider.com/6421aec7b50c2900186414bc?width=1200&format=jpeg', '2023-03-27 16:16:26', 'Nvidia is looking beyond crypto as it shifts its focus to artificial intelligence, according to a recent interview with Nvidia CTO Michael Kagan.\r\nCrypto miners feverishly bought GPUs from Nvidia dur… [+1875 chars]', 'business-insider'),
(79, 'Business Insider', 'Morgan Chittum', 'Dogecoin has surged 24% in a month, outperforming major cryptos on Elon Musk\'s antics', 'Dogecoin added to gains on Monday, spiking 6%. Elon Musk has offered a million dogecoin to whoever can prove his family owned an emerald mine.', 'https://markets.businessinsider.com/news/currencies/dogecoin-price-elon-musk-twitter-crypto-market-outlook-bitcoin-ethereum-2023-4', 'https://i.insider.com/643d3b1556f0dc0019895edc?width=1200&format=jpeg', '2023-04-17 15:37:07', 'Carina Johansen/NTB/AFP via Getty Images\r\n<ul>\n<li>Dogecoin has jumped 24% in the past month, according to Messari.</li>\n<li>The token\'s price often fluctuates on comments from Twitter and Tesla CEO … [+1783 chars]', 'business-insider'),
(80, 'Business Insider', 'Jason Ma', 'US stocks climb on strong Chinese economic growth and upbeat earnings', 'Bank of America and Johnson & Johnson beat first-quarter earnings views, while Goldman Sachs missed.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-china-gdp-growth-goldman-sachs-earnings-2023-4', 'https://i.insider.com/63975699a3bebb0018b40e0e?width=1200&format=jpeg', '2023-04-18 13:33:56', 'Traders work on the floor of the New York Stock Exchange (NYSE) on October 27, 2022 in New York City.Spencer Platt/Getty Images\r\n<ul>\n<li>US stocks rose Tuesday as China\'s first-quarter GDP growth of… [+2045 chars]', 'business-insider'),
(81, 'Business Insider', 'mchittum@insider.com (Morgan Chittum)', 'US stocks jump as traders hope worst of banking crisis has passed', 'Morgan Stanley\'s top strategist said the fallout in the banking sector starts what\'s likely to be the \"vicious\" end to the bear market in stocks.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-bank-crisis-credit-suisse-ubs-svb-2023-3', 'https://i.insider.com/63dba59ee33c4000193aa450?width=1200&format=jpeg', '2023-03-20 20:17:28', 'US stocks rallied on Monday as traders digested efforts to contain a banking crisis and braced for the next policy decision from Federal Open Market Committee meeting this week.\r\nOver the weekend, UB… [+2029 chars]', 'business-insider'),
(82, 'Business Insider', 'mfox@businessinsider.com (Matthew Fox)', 'US stocks rise as fresh jobs data continues to show no sign of labor market weakness', 'The strength in the labor market continues even as high-profile tech companies like Amazon and Meta Platforms announce more deep job cuts.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-us-jobs-market-resilience-jobless-claims-2023-3', 'https://i.insider.com/641c4f0fb7834100191aeb53?width=1200&format=jpeg', '2023-03-23 13:35:35', 'US stocks jumped on Thursday as the US labor market continued to show signs of remarkable resilience despite ongoing rate hikes from the Federal Reserve and a recent banking crisis.\r\nWeekly jobless c… [+2211 chars]', 'business-insider'),
(83, 'Business Insider', 'Morgan Chittum', 'US stocks jump as traders put bank crisis behind them and brace for more inflation data', 'Investors are preparing for key market data on Friday that will help gauge inflationary pressures on the US economy.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-bank-crisis-sp500-nasdaq-inflation-recession-fed-2023-3', 'https://i.insider.com/62bad7662224c3001813f01e?width=1200&format=jpeg', '2023-03-30 20:05:22', 'Traders on the floor of the New York Stock Exchange (NYSE)Spencer Platt/Getty Images\r\n<ul>\n<li>US stocks marched higher on hopes that global banking turmoil has finally settled. </li>\n<li>The S&P 500… [+2387 chars]', 'business-insider'),
(84, 'Business Insider', 'Matthew Fox', 'US stocks extend gains as volatility recedes amid softer rate forecasts', 'The VIX fell below 19 on Monday, marking its seventh consecutive daily decline as rate fears and banking jitters recede.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-volatility-drops-seventh-consecutive-day-vix-2023-4', 'https://i.insider.com/5f5792abe6ff30001d4e771f?width=1200&format=jpeg', '2023-04-04 13:37:53', 'Traders work on the floor of the New York Stock Exchange shortly after the opening bell in New York, U.S., March 17, 2020.Lucas Jackson/Reuters\r\n<ul><li>US stocks extended their gains on Tuesday as m… [+2309 chars]', 'business-insider'),
(85, 'Business Insider', 'Morgan Chittum', 'US stocks drop as traders digest jobs data that shows hiring slowed in March', 'The Federal Reserve\'s year-long campaign to cool down the economy may finally be weighing on the labor market.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-traders-jobs-data-inflation-recession-bonds-oil-2023-4', 'https://i.insider.com/640f546aa3b2a10018b2b2f1?width=1200&format=jpeg', '2023-04-05 13:48:14', 'TIMOTHY A. CLARY / Getty\r\n<ul>\n<li>US stocks edge lower on Wednesday as traders worry about the direction of the overall economy.</li>\n<li>The S&P 500 and Dow Jones Industrial Average ended their fou… [+2125 chars]', 'business-insider'),
(86, 'Business Insider', 'Jennifer Sor', 'Dow jumps 400 points to end tumultuous first quarter as markets move on from bank crisis', 'The S&P 500 and Nasdaq Composite saw a winning quarter, gaining 6% and 17%, respectively, since the start of the year.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-sp500-nasdaq-dow-bull-rally-q1-2023-3', 'https://i.insider.com/5e70c0d9c4854064de57e3f2?width=1200&format=jpeg', '2023-03-31 20:07:43', 'Traders work on the floor of the New York Stock Exchange (NYSE) in New York City, New York, U.S., March 10, 2020.Andrew Kelly/Reuters\r\n<ul>\n<li>US stocks jumped on Friday, ending the first quarter on… [+2374 chars]', 'business-insider'),
(87, 'Business Insider', 'Matthew Fox', 'US stocks trade mixed as investors prepare for first-quarter earnings results', 'Wall Street analysts have lowered their Q1 S&P 500 earnings estimates to $50.76 per share from $54.13 at the start of the year.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-investors-prepare-first-quarter-earnings-results-2023-4', 'https://i.insider.com/5f4fb1da7ed0ee001e25cfb0?width=1200&format=jpeg', '2023-04-11 13:38:46', 'Lucas Jackson/Reuters\r\n<ul><li>US stocks traded mixed on Tuesday as investors prepare for first-quarter earnings results.</li><li>The mega-cap banks including JPMorgan and Wells Fargo are scheduled t… [+2509 chars]', 'business-insider'),
(88, 'Business Insider', 'Morgan Chittum', 'US stocks trade mixed as traders wait for next wave of corporate earnings reports', 'Bank of America, Goldman Sachs, and Tesla are all expected to deliver quarterly results this week.', 'https://markets.businessinsider.com/news/stocks/stock-markets-news-dow-nasdaq-corporate-quarterly-earnings-inflation-fed-2023-4', 'https://i.insider.com/643d429556f0dc0019895fcf?width=1200&format=jpeg', '2023-04-17 13:36:54', 'Stock tradersDrew Angerer/Getty Images\r\n<ul>\n<li>Moves in stock indexes were muted Monday on corporate earnings uncertainty.</li>\n<li>First-quarter earnings kicked off on Friday, with strong results … [+1847 chars]', 'business-insider'),
(89, 'Business Insider', 'Jennifer Sor', 'US stocks trade mixed as investors assess wave of earnings results from big companies', 'Earnings season has kicked off in earnest. Investors are looking past results from the biggest banks and getting ready for big tech firms to report.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-bofa-gs-jnj-corporate-earnings-economy-2023-4', 'https://i.insider.com/5e7cc4132d41c150481afc74?width=1200&format=jpeg', '2023-04-18 20:24:04', 'Traders work on the floor of the New York Stock Exchange (NYSE) in New York, U.S., March 20, 2020Lucas Jackson/Reuters\r\n<ul>\n<li>Stocks traded mixed on Tuesday as investors digested the wave of earni… [+2430 chars]', 'business-insider'),
(90, 'Business Insider', 'Phil Rosen', 'US stocks climb as fresh signs point to cooling inflation and a softer labor market', 'The March producer price index declined 0.5% month-over-month, more than expected, while weekly jobless claims were higher than estimates.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-ppi-cooling-inflation-data-jobless-claims-2023-4', 'https://i.insider.com/643801285f081b0019c0f9b1?width=1200&format=jpeg', '2023-04-13 13:41:37', 'Spencer Platt/Getty Images\r\n<ul>\n<li>US stocks climbed Thursday as investors took in new economic data that pointed to cooling inflation. </li>\n<li>Thursday data showed the March producer price index… [+2162 chars]', 'business-insider'),
(91, 'Business Insider', 'Jennifer Sor', 'Dow soars 383 points as US stocks jump on more signs inflation is falling', 'Data on Thursday showed that wholesale inflation tumbled in March to its lowest level since January 2021.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-inflation-march-ppi-dow-jones-economy-2023-4', 'https://i.insider.com/6219465caa07b20019fa1bc4?width=1200&format=jpeg', '2023-04-13 20:13:25', 'Brendan McDermid/Reuters\r\n<ul>\n<li>US stocks jumped on Thursday on more signs of falling inflation and a cooling labor market.</li>\n<li>Investors cheered data that showed a big drop in the Producer P… [+2316 chars]', 'business-insider'),
(92, 'MakeUseOf', 'Temitope Olatunji', 'What Is Binance Auto-Invest and How Does It Work?', 'You can now regularly buy Bitcoin and other cryptos with Binance.', 'https://www.makeuseof.com/what-is-binance-auto-invest-how-does-it-work/', 'https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/04/a-picture-of-a-hand-carrying-a-phone-with-binance-chart.jpg', '2023-04-18 15:00:16', 'Investing in cryptocurrencies requires studying price charts and spotting the right opportunities, which can sometimes be stressful depending on your strategy and what you want to achieve. But with B… [+5124 chars]', ''),
(93, 'MakeUseOf', 'Dmytro Spilka', 'What\'s the Difference Between a Litecoin Halving and a Bitcoin Halving?', 'Both Bitcoin and Litecoin have halving events. But what\'s the difference between the two?', 'https://www.makeuseof.com/litecoin-vs-bitcoin-halving/', 'https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/03/litecoin.jpg', '2023-04-18 12:00:17', 'Often dubbed \"the silver to Bitcoin\'s gold,\" Litecoin shares many properties with the world\'s oldest and most famous cryptocurrency. Both assets have a fixed scarcity, a proof-of-work (PoW) mining sy… [+5466 chars]', ''),
(94, 'Korben.info', 'Korben', 'Récupérez vos Bitcoins perdus en un instant avec Bitcoin Recovery', 'Vous le savez, le Bitcoin c’est une révolution monétaire comme jamais vue auparavant. Ça permet de s’affranchir des liens avec les états et de pouvoir être garant de son propre argent. Bref, le Bitcoin, c’est la liberté et beaucoup de gens s’y sont mis ces de…', 'https://korben.info/bitcoin-recovery.html', 'https://korben.info/app/uploads/2023/03/Manu23_someone_very_happy_to_discover_Bitcoin_96be072b-c1ed-401b-b09f-78273fe54fd1.webp', '2023-04-01 06:00:00', 'Vous le savez, le Bitcoin c’est une révolution monétaire comme jamais vue auparavant. Ça permet de s’affranchir des liens avec les états et de pouvoir être garant de son propre argent.\r\nBref, le Bitc… [+3300 chars]', ''),
(95, 'Presse-citron', 'RPB', 'Voici où se cache la bible du Bitcoin dans votre Mac depuis 5 ans', 'Cette découverte risque de vous emboucher un Bitcoin !', 'https://www.presse-citron.net/?p=547530', 'https://www.presse-citron.net/app/uploads/2023/04/mac-bitcoin.jpg', '2023-04-06 12:15:20', '<ul><li>Surprise : le White Paper du Bitcoin se cache dans tous les Mac de la planète depuis 5 ans</li><li>Apple n’a pourtant jamais affiché de soutien clair aux cryptomonnaies – si bien qu’il s’agit… [+3266 chars]', ''),
(96, 'Genbeta.com', 'Eva Rodriguez', 'El documento técnico del Bitcoin está oculto en todas las copias de las últimas versiones de macOS. Así puedes verlo en tu Mac', 'Con el terminal de un ordenador puedes ejecutar muchas acciones de forma directa entre el comando que tecleas y su consecuencia, lo que resulta muy útil tanto para el sistema como para otras máquinas en red. Pero también se esconden sorpresas ocultas tan incr…', 'https://www.genbeta.com/sistemas-operativos/documento-tecnico-bitcoin-esta-oculto-todas-copias-ultimas-versiones-macos-asi-puedes-verlo-tu-mac', 'https://i.blogs.es/899aa0/kanchanara-pcmwbd6ufyo-unsplash/840_560.jpeg', '2023-04-06 12:00:42', 'Con el terminal de un ordenador puedes ejecutar muchas acciones de forma directa entre el comando que tecleas y su consecuencia, lo que resulta muy útil tanto para el sistema como para otras máquinas… [+3756 chars]', ''),
(97, 'Genbeta.com', 'Bárbara Bécares', 'Elon Musk vuelve a jugar con el valor de las criptomonedas a su favor: shiba inu es el logo de Twitter y Dogecoin crece un 30%', 'Elon Musk juega con el valor de las criptomonedas a su antojo desde su querida red social Twitter. Antes de comprarla y ser el dueño de la plataforma, ya era un usuario muy activo. Al igual que es activo en el mundo de las criptomonedas (aunque se deshizo de …', 'https://www.genbeta.com/actualidad/elon-musk-vuelve-a-jugar-valor-criptomonedas-a-su-favor-shiba-inu-logo-twitter-dogecoin-crece-30', 'https://i.blogs.es/9302d8/1366_2000/840_560.jpeg', '2023-04-04 05:20:21', 'Elon Musk juega con el valor de las criptomonedas a su antojo desde su querida red social Twitter. Antes de comprarla y ser el dueño de la plataforma, ya era un usuario muy activo. Al igual que es ac… [+2042 chars]', ''),
(98, 'Presse-citron', 'Hadrien Augusto', '70 % de hausse : voici le Bitcoin de 2023, outsider et indépendant', 'Son cours a encore explosé au cours du week-end. Le Bitcoin est proche de son record des 9 derniers mois. Crise bancaire et retour des liquidités expliquent son avènement soudain.', 'https://www.presse-citron.net/70-de-hausse-bitcoin-2023/', 'https://www.presse-citron.net/app/uploads/2023/03/bitcoin-2023-retour-raisons.jpg', '2023-03-20 13:04:50', 'Qui aurait pu croire que linflation puisse devenir une tendance opportune pour le Bitcoin ? Au cours du dernier week-end, son prix a dépassé les 28 000 dollars, un palier quil navait plus jamais tuto… [+3767 chars]', ''),
(99, 'Business Insider', 'Carla Mozée', 'US stocks trade mixed as oil surges on unexpected production cut by OPEC+', 'The second quarter kicked off with an announcement by OPEC+ stating production cuts of 1.6 million a barrels a day would begin next month.', 'https://markets.businessinsider.com/news/stocks/stock-market-news-today-oil-prices-opec-tech-nasdaq-dow-2023-4', 'https://i.insider.com/634992172f7a5a00185286f9?width=1200&format=jpeg', '2023-04-03 13:39:54', 'Traders work on the New York Stock Exchange floor in New York City.AP Photo/Ted Shaffrey\r\n<ul>\n<li>US stocks were mixed Monday, with oil prices in focus. </li>\n<li>Yields rose with oil prices surging… [+2625 chars]', 'business-insider'),
(100, 'Business Insider', 'tmohamed@insider.com (Theron Mohamed)', '\'Big Short\' investor Michael Burry says Jerome Powell should butt out and let markets set asset prices', 'Michael Burry called for Fed Chair Jerome Powell to stop sharing his thoughts and interfering in markets, suggesting that distorts asset prices.', 'https://markets.businessinsider.com/news/stocks/big-short-michael-burry-fed-powell-asset-prices-interest-rates-2023-3', 'https://i.insider.com/64109b5f9aa2e6001956d8d4?width=1200&format=jpeg', '2023-03-27 15:16:56', 'Jerome Powell should stop sharing his views and interfering in markets, Michael Burry has said.\r\n\"Powell should have just said \'I don\'t know,\'\" the investor of \"The Big Short\" fame tweeted on Saturda… [+2983 chars]', 'business-insider');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `newsdata`
--
ALTER TABLE `newsdata`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `newsdata`
--
ALTER TABLE `newsdata`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
